name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

env:
  REGION: southamerica-east1
  PROJECT: vital-domain-436623-b8
  REPO: navgo
  IMAGE: navgo-api

jobs: 
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set variables
        run: echo "IMAGE_TAG=$REGION-docker.pkg.dev/$PROJECT/$REPO/$IMAGE:latest" >> $GITHUB_ENV

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GC_DEPLOYER_KEY }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Docker auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3 

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ${IMAGE} \
            --image "${{ env.IMAGE_TAG }}" \
            --region "${{ env.REGION }}" \
            --platform managed \
            --allow-unauthenticated \
            --port 3333
