name: Build and Deploy to GCP

on:
  push:
    branches:
      - workflow-error

env:
  REGION: southamerica-east1
  PROJECT: vital-domain-436623-b8
  REPO: navgo
  IMAGE: navgo-api

jobs: 
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set variables
        run: echo "IMAGE_TAG=$REGION-docker.pkg.dev/$PROJECT/$REPO/$IMAGE:latest" >> $GITHUB_ENV
      
      - name: Create app directory
        run: mkdir -p ./app

      - name: Create gcp-credentials.json env file
        run: echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > ./app/gcp-credentials.json

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GC_DEPLOYER_KEY }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Docker auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3 

      - name: Check for gcp-credentials.json
        run: ls -al ./app

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ${IMAGE} \
            --image "${{ env.IMAGE_TAG }}" \
            --region "${{ env.REGION }}" \
            --platform managed \
            --allow-unauthenticated \
            --port 3333 \
            --set-env-vars "ROOT_PASSWORD=${{ secrets.ROOT_PASSWORD }},DB_NAME=${{ secrets.DB_NAME }},DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},SECURITY_KEY=${{ secrets.SECURITY_KEY }},DB_URL=${{ secrets.DB_URL }},PROJECT_ID=${{ secrets.PROJECT_ID }},GOOGLE_APPLICATION_CREDENTIALS_PATH=gcp-credentials.json"
